#!/usr/bin/env python3
"""Auto scale (scottland-output set NAME --scale auto, or `scale = auto` in the config): the natural
scale core works out from what the compositor reports for an output, and the resolver that writes it
into the assembled config in place of each output's winning auto (core/libexec/
scottland_output_scale.py). Checked on output reports shaped like scottland-output-heads';
tests/output-control-test.sh checks the numbers Wayfire applies.

  tests/output-scale-unit.py
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "core/libexec"))
from scottland_output_scale import WAITING, natural_scale, resolve  # noqa: E402


def head(width, height, physical_width, physical_height, enabled=True):
    mode = {"width": width, "height": height, "refresh": 60.0}
    return {"name": "X", "physical_width": physical_width, "physical_height": physical_height,
            "enabled": enabled, "mode": mode if enabled else None,
            "modes": [{**mode, "preferred": True}, {"width": 1280, "height": 800, "refresh": 60.0,
                                                    "preferred": False}]}


failed = 0


def check(label, got, want):
    global failed
    ok = got == want
    print(("PASS " if ok else "FAIL ") + label + ("" if ok else f": got {got}, want {want}"))
    failed += not ok


check("HiDPI laptop panel (14in 2880x1800, 302x189 mm, ~242 ppi): 2",
      natural_scale(head(2880, 1800, 302, 189)), 2)
check("13in laptop panel (1920x1200, 286x179 mm, ~170 ppi): 1.5",
      natural_scale(head(1920, 1200, 286, 179)), 1.5)
check("27in 4K monitor (3840x2160, 597x336 mm, ~163 ppi): 1.5",
      natural_scale(head(3840, 2160, 597, 336)), 1.5)
check("ordinary desktop monitor (27in 2560x1440, 597x336 mm, ~109 ppi): 1",
      natural_scale(head(2560, 1440, 597, 336)), 1)
check("ordinary desktop monitor (24in 1920x1080, 527x296 mm, ~92 ppi): 1",
      natural_scale(head(1920, 1080, 527, 296)), 1)
check("no physical size (projector, virtual output): 1",
      natural_scale(head(3840, 2160, 0, 0)), 1)
check("the mode being set counts, not the current one (HiDPI panel set to 1280x800): 1",
      natural_scale(head(2880, 1800, 302, 189), "1280x800@60000"), 1)
check("a mode that isn't a size (auto, mirror) uses the current mode",
      natural_scale(head(2880, 1800, 302, 189), "auto"), 2)
check("a disabled output uses its preferred mode",
      natural_scale(head(2880, 1800, 302, 189, enabled=False)), 2)
check("every result is an exact step of Wayfire's 1/120 scale",
      all(natural_scale(head(w, h, 302, 189)) * 120 % 1 == 0
          for w, h in ((800, 500), (1440, 900), (1920, 1200), (2560, 1600), (2880, 1800))), True)


def scales(text):
    """Each scale line of TEXT without its comment, in order."""
    return [line.split("#")[0].strip() for line in text.split("\n") if line.strip().startswith("scale")]


panel, desktop, virtual = head(2880, 1800, 302, 189), head(2560, 1440, 597, 336), head(1280, 720, 0, 0)
outputs = {"eDP-1": panel, "DP-1": desktop, "HEADLESS-1": virtual}
catch_all = ("[output]\nscale = 1\n\n# ---- generated by 50-integration\n"
             "[output:eDP-1]\nscale = auto\n[output:DP-1]\nscale = auto\n[output:HEADLESS-1]\nscale = auto\n")
check("an integration's catch-all auto: HiDPI panel 2, ordinary monitor 1, no physical size 1",
      scales(resolve(catch_all, outputs)), ["scale = 1", "scale = 2", "scale = 1", "scale = 1"])
check("an earlier auto, then a later section for the output with no scale line: auto still wins",
      scales(resolve("[output:eDP-1]\nscale = auto\nposition = 0,0\n[output:eDP-1]\nmode = 2880x1800\n",
                     outputs)), ["scale = 2"])
overridden = "[output:eDP-1]\nscale = auto\n[output:eDP-1]\n# overrides.ini\nscale = 1.25\n"
check("a later number (overrides.ini) beats an integration's auto: both lines stay as they are",
      resolve(overridden, outputs), overridden)
check("a later auto beats an earlier number: only the winning line becomes a number",
      scales(resolve("[output:eDP-1]\nscale = 1.25\n[output:eDP-1]\nscale = auto\n", outputs)),
      ["scale = 1.25", "scale = 2"])
check("the winning mode line counts (HiDPI panel set to 1280x800 in a later section): 1",
      scales(resolve("[output:eDP-1]\nscale = auto\n[output:eDP-1]\nmode = 1280x800@60000\n", outputs)),
      ["scale = 1"])
check("an output the compositor doesn't report: 1",
      scales(resolve("[output:DP-9]\nscale = auto\n", outputs)), ["scale = 1"])
waiting = resolve("[output:eDP-1]\nscale = auto\n", None)
check("before the compositor runs: 1, marked for the rebuild at session start",
      (scales(waiting), WAITING in waiting), (["scale = 1"], True))
check("the plain [output] section is left alone (Wayfire's defaults for every output)",
      resolve("[output]\nscale = auto\n", outputs), "[output]\nscale = auto\n")
plain = "[output:eDP-1]\nposition = 0,0 \\\nscale = auto\n[output:DP-1]\nscale = 2 # auto\n"
check("a config without a winning auto is unchanged (continued values and comments are not scale lines)",
      resolve(plain, outputs), plain)

print(f'{"FAIL" if failed else "PASS"}: {failed} failed')
sys.exit(1 if failed else 0)
