#!/usr/bin/env python3
"""File wins (docs/rulings.md 10-07; S4-S6, S21) via real stipc input in a caller-owned headless
session: hand edits of layout.ini and solar.ini reach the running desktop and the open panel,
and Save edits the files in place. Run through tests/settings-file-wins-test.sh.

The headless session doesn't run the config watcher (06-watch-config), so after each layout.ini
write the test rewrites the session's assembled config the way the watcher's rebuild would:
the assembled base followed by layout.ini, written in place for Wayfire to reload.
"""
from importlib.machinery import SourceFileLoader
import json
import os
from pathlib import Path
import socket
import struct
import subprocess
import sys
import time

repo = Path(__file__).resolve().parents[1]
session = Path(sys.argv[1])
art = repo / "build/settings-file-wins-evidence" / f"run-{os.getpid()}-{time.time_ns()}"
art.mkdir(parents=True)
# The file 20-layout-settings reads in this session (tests/headless.sh: XDG_CONFIG_HOME).
layout = session / "config/scottland/layout.ini"
solar = art / "solar.ini"
assembled = session / "wayfire.ini"
base = assembled.read_text()
layout.unlink(missing_ok=True)
ctl = str(repo / "core/libexec/scottland-ctl")
solar_reader = SourceFileLoader("scottland_solar", str(repo / "core/libexec/scottland-solar-theme")).load_module()
solar_reader.CONFIG = solar

sock = socket.socket(socket.AF_UNIX)
sock.connect(os.environ["WAYFIRE_SOCKET"])
log = (art / "panel.log").open("w")
clients = []
passed = failed = 0
panel = None


def ipc(method, data=None):
    body = json.dumps(dict(method=method, data=data or {})).encode()
    sock.sendall(struct.pack("<I", len(body)) + body)
    def read(n):
        result = b""
        while len(result) < n:
            chunk = sock.recv(n - len(result))
            if not chunk:
                raise RuntimeError("compositor disconnected")
            result += chunk
        return result
    result = json.loads(read(struct.unpack("<I", read(4))[0]))
    if isinstance(result, dict) and "error" in result:
        raise RuntimeError(f"{method}: {result}")
    return result


def check(name, condition):
    global passed, failed
    print(("PASS " if condition else "FAIL ") + name, flush=True)
    passed += bool(condition)
    failed += not condition


def option(name):
    return float(ipc("wayfire/get-config-option", {"option": "scottland/" + name})["value"])


def wait_for(probe, timeout=3):
    # Wait on the observed state; the input or file change under test is never repeated.
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            if probe():
                return True
        except (KeyError, TypeError, json.JSONDecodeError, subprocess.CalledProcessError):
            pass
        time.sleep(.03)
    return False


def option_reaches(name, expected, timeout=3):
    return wait_for(lambda: abs(option(name) - expected) < .01, timeout)


def rebuild():
    """What the config watcher does after layout.ini changes (scottland-build-config)."""
    text = layout.read_text() if layout.exists() else ""
    text = "\n".join(line.replace("goo_dye_strength", "goo_dye_density", 1) if line.lstrip().startswith("goo_dye_strength")
                     else line for line in text.split("\n"))
    with assembled.open("w") as out:  # in place, as the builder writes it
        out.write(base + "\n# ---- generated by 20-layout-settings (test)\n" + text)


def hand_edit(path, text, replace=False):
    """An editor's save: in place, or (replace=True) a new file renamed over the old one."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if replace:
        new = path.with_name(path.name + ".new")
        new.write_text(text)
        os.replace(new, path)
    else:
        with path.open("w") as out:
            out.write(text)
    if path == layout:
        rebuild()


def key(code):
    ipc("stipc/feed_key", dict(key=code, state=True))
    time.sleep(.03)
    ipc("stipc/feed_key", dict(key=code, state=False))
    time.sleep(.12)


def click(x, y):
    ipc("stipc/move_cursor", dict(x=round(x), y=round(y)))
    time.sleep(.08)
    ipc("stipc/feed_button", dict(combo="BTN_LEFT", mode="press"))
    ipc("stipc/feed_button", dict(combo="BTN_LEFT", mode="release"))
    time.sleep(.15)


def settings_quickshell_pid(wrapper_pid):
    deadline = time.monotonic() + 5
    while time.monotonic() < deadline:
        pending, seen = [wrapper_pid], set()
        while pending:
            pid = pending.pop()
            if pid in seen:
                continue
            seen.add(pid)
            try:
                comm = Path(f"/proc/{pid}/comm").read_text().strip()
                argv = Path(f"/proc/{pid}/cmdline").read_bytes().decode(errors="replace").split("\0")
            except (FileNotFoundError, PermissionError, ProcessLookupError):
                continue
            if comm == "quickshell" and str(repo / "core/settings") in argv:
                return pid
            try:
                pending.extend(int(c) for c in Path(f"/proc/{pid}/task/{pid}/children").read_text().split())
            except (FileNotFoundError, PermissionError, ProcessLookupError, ValueError):
                pass
        time.sleep(.03)
    raise RuntimeError(f"could not find QuickShell below test wrapper PID {wrapper_pid}")


def snapshot():
    return json.loads(subprocess.check_output(
        ["qs", "ipc", "--pid", str(panel.qml_pid), "call", "settings-test", "snapshot"], text=True, timeout=5))


def open_panel():
    global panel, panel_x, panel_y
    panel = subprocess.Popen(["qs", "-n", "-p", str(repo / "core/settings")],
        env=dict(os.environ, QS_DISABLE_FILE_WATCHER="1", SCOTTLAND_CTL=ctl,
                 SCOTTLAND_LAYOUT_FILE=str(layout), SCOTTLAND_SOLAR_FILE=str(solar),
                 SCOTTLAND_SETTINGS_TEST="1"), stdout=log, stderr=log)
    clients.append(panel)
    panel.qml_pid = settings_quickshell_pid(panel.pid)
    check("settings maps", wait_for(lambda: snapshot().get("screen"), 5) and panel.poll() is None)
    time.sleep(.4)
    output = next(o for o in ipc("window-rules/list-outputs") if o["name"] == snapshot()["screen"])
    g, p = output["geometry"], snapshot()["panel"]
    panel_x = g["x"] + (g["width"] - p["width"]) / 2
    panel_y = g["y"] + g["height"] - max(24, round(g["height"] * .04)) - p["height"]


def close_panel(save=False):
    key("KEY_ENTER" if save else "KEY_ESC")
    panel.wait(timeout=5)
    time.sleep(.15)


def zone_row(index):
    # Zone rows: 0 Center edge softness, 1 Center zone width, 2 Widget rail width.
    z = snapshot()["zones"]
    click(panel_x + z["x"] + 200 - panel_x_origin(), panel_y + z["y"] + 34 + 69 * index)


def panel_x_origin():
    output = next(o for o in ipc("window-rules/list-outputs") if o["name"] == snapshot()["screen"])
    return output["geometry"]["x"]


def goo_row(name):
    q = snapshot()
    click(panel_x + 36 + 1.5 * (q["panel"]["width"] - 72) / 6, panel_y + 100)  # Goo tab
    if not wait_for(lambda: snapshot()["tab"] == 1):
        raise RuntimeError(f"Goo tab click left tab {snapshot()['tab']}")
    q = snapshot()
    g = q["goo"]
    row = q["goo"]["rows"].index(name)
    y = g["y"] + row * g["rowHeight"] + 34
    v = q["viewport"]
    if y > v["y"] + v["height"] - 24:
        raise RuntimeError(f"goo row {name} is below the viewport")
    click(panel_x + g["x"] + 240 - panel_x_origin(), panel_y + y)


def lines(path, key_name):
    return [l for l in path.read_text().split("\n") if l.split("=")[0].strip() == key_name]


try:
    # --- Settings Save, then a hand edit: the file wins on the running desktop -------------------
    open_panel()
    zone_row(1)
    before = option("center_width")
    key("KEY_RIGHT")
    stepped = round((before + .5) * 2) / 2
    check("S3 zone change previews live", option_reaches("center_width", stepped))
    goo_row("goo_thickness")
    thickness = option("goo_thickness")
    key("KEY_RIGHT")
    check("S3 Goo change previews live", option_reaches("goo_thickness", thickness + 1))
    close_panel(save=True)
    check("S4 Save writes the zone value", lines(layout, "center_width") == [f"center_width = {stepped:.3f}"])
    check("S4 Save writes the Goo value", lines(layout, "goo_thickness") == [f"goo_thickness = {thickness + 1:g}"])
    rebuild()
    hand_edit(layout, layout.read_text().replace(f"center_width = {stepped:.3f}", "center_width = 41"))
    check("file wins: a hand-edited zone value set in Settings takes effect live", option_reaches("center_width", 41))
    hand_edit(layout, layout.read_text().replace(f"goo_thickness = {thickness + 1:g}", "goo_thickness = 21"), replace=True)
    check("file wins: a replaced layout.ini's Goo value set in Settings takes effect live",
          option_reaches("goo_thickness", 21))

    # --- Settings Cancel, then a hand edit ---------------------------------------------------------
    open_panel()
    check("S4 reopening shows the hand-edited values",
          abs(snapshot()["layout"]["center_width"] - 41) < .01 and snapshot()["values"]["goo_thickness"] == 21)
    zone_row(1)
    key("KEY_RIGHT")
    check("S3 previewed zone change before Cancel", option_reaches("center_width", 41.5))
    close_panel()
    check("S5 Cancel restores the zone value", option_reaches("center_width", 41))
    hand_edit(layout, layout.read_text().replace("center_width = 41", "center_width = 43"))
    check("file wins: a hand edit after Cancel takes effect live", option_reaches("center_width", 43))

    # --- Hand edits while the panel is open -------------------------------------------------------
    open_panel()
    zone_row(2)
    rail = snapshot()["layout"]["rail_width"]
    key("KEY_RIGHT")
    check("unsaved rail change previews", wait_for(lambda: abs(option("rail_width") - (rail + .1)) < .01))
    hand_edit(layout, layout.read_text().replace("center_width = 43", "center_width = 45"))
    check("open panel shows a hand-edited zone value", wait_for(lambda: abs(snapshot()["layout"]["center_width"] - 45) < .01))
    check("open panel takes the hand edit as the Cancel value",
          wait_for(lambda: abs(snapshot()["original"]["center_width"] - 45) < .01))
    check("the hand edit is live while the panel is open", option_reaches("center_width", 45))
    check("an unsaved change to another setting stays", abs(snapshot()["layout"]["rail_width"] - (rail + .1)) < .01)
    hand_edit(layout, layout.read_text().replace("goo_thickness = 21", "goo_thickness = 23"), replace=True)
    check("open panel follows a replaced layout.ini", wait_for(lambda: snapshot()["values"]["goo_thickness"] == 23))
    check("a replaced layout.ini is live while the panel is open", option_reaches("goo_thickness", 23))
    hand_edit(solar, "[solar]\nenabled = no\n")
    check("open panel follows a hand-edited solar.ini", wait_for(lambda: snapshot()["solar"]["enabled"] is False))
    close_panel()
    check("Cancel keeps the hand-edited value", option_reaches("center_width", 45))
    check("Cancel restores the unsaved change", option_reaches("rail_width", rail))
    check("Cancel leaves the hand-edited solar.ini", solar.read_text() == "[solar]\nenabled = no\n")

    # --- A key removed from layout.ini while the panel is open ------------------------------------
    open_panel()
    hand_edit(layout, "\n".join(l for l in layout.read_text().split("\n") if not l.startswith("center_width")))
    check("a removed setting shows its shipped default", wait_for(lambda: abs(snapshot()["layout"]["center_width"] - 33.333) < .01))
    layout.unlink()
    rebuild()
    check("a deleted layout.ini leaves the panel running on shipped defaults",
          wait_for(lambda: snapshot()["values"]["goo_thickness"] == 13) and panel.poll() is None)
    close_panel()

    # --- Save keeps what it doesn't manage --------------------------------------------------------
    # Written while the panel is open, so the panel's values come from its own reading of the file.
    open_panel()
    hand_edit(layout, "# my layout\n[scottland]\ncenter_width = 30  # narrow\nfuture_setting = 7\n"
              "goo_dye_strength = 0.6\ncenter_width = 35\nrail_width = wide\n\n[elsewhere]\ncenter_width = 99\nnote = kept\n")
    check("Settings reads the last center_width line as Wayfire does",
          wait_for(lambda: abs(snapshot()["layout"]["center_width"] - 35) < .01))
    check("Settings reads the legacy dye strength line", abs(snapshot()["values"]["goo_dye_density"] - .6) < .01)
    check("Settings ignores an invalid value as Wayfire does", abs(snapshot()["layout"]["rail_width"] - 2) < .01)
    close_panel(save=True)
    text = layout.read_text()
    check("Save keeps comments", text.startswith("# my layout\n"))
    check("Save keeps unknown keys", "future_setting = 7" in text)
    check("Save keeps other sections", "[elsewhere]\ncenter_width = 99\nnote = kept" in text)
    check("Save writes one center_width line in [scottland]", lines(layout, "center_width") == ["center_width = 35.000", "center_width = 99"])
    check("Save renames the legacy dye line", "goo_dye_strength" not in text and "goo_dye_density = 0.6" in text)
    check("Save replaces the invalid line", lines(layout, "rail_width") == ["rail_width = 2.000"])
    check("Save adds settings the file didn't have", lines(layout, "goo_thickness") == ["goo_thickness = 13"])
    rebuild()
    check("the saved file still applies", option_reaches("center_width", 35))

    # --- solar.ini parsing matches scottland-solar-theme -----------------------------------------
    for name, fixture in (
            ("yes/off", "[solar]\nenabled = yes\nallow_ip = off\n"),
            ("On/1", "[solar]\nenabled = On\nallow_ip = 1\n"),
            ("unrecognized values", "[solar]\nenabled = sure\nallow_ip = nope\n"),
            ("keys outside [solar]", "[elsewhere]\nenabled = false\nallow_ip = false\n[solar]\nallow_ip = yes\n"),
            ("no [solar] section", "[other]\nenabled = false\n"),
            ("location", "[solar]\nlocation_set = on\nlatitude = 12.5\nlongitude = -45\n")):
        hand_edit(solar, fixture)
        expected = solar_reader.read_config()
        open_panel()
        s = snapshot()["solar"]
        location = (float(s["latitude"]), float(s["longitude"])) if s["location_set"] else None
        check("S21 Settings reads solar.ini as Sunlight does: " + name,
              (s["enabled"], s["allow_ip"], location) == (expected["enabled"], expected["allow_ip"], expected["location"]))
        close_panel()

    hand_edit(solar, "# sunlight\n[solar]\nenabled = yes\nfuture_solar = 3\n\n[extra]\nx = 1\n")
    open_panel()
    q = snapshot()
    click(panel_x + 36 + 5.5 * (q["panel"]["width"] - 72) / 6, panel_y + 100)  # Sunlight tab
    check("Sunlight tab selects", wait_for(lambda: snapshot()["tab"] == 5))
    e = snapshot()["solarEnable"]
    click(panel_x + e["x"] + e["width"] / 2 - panel_x_origin(), panel_y + e["y"] + 21)
    check("Sunlight switch turns off", wait_for(lambda: snapshot()["solar"]["enabled"] is False))
    close_panel(save=True)
    text = solar.read_text()
    check("S21 Save keeps solar.ini comments, unknown keys and sections",
          text.startswith("# sunlight\n[solar]\n") and "future_solar = 3" in text and "[extra]\nx = 1" in text)
    check("S21 Save writes one enabled line", lines(solar, "enabled") == ["enabled = false"])
    check("S21 Sunlight reads the saved file", solar_reader.read_config()["enabled"] is False)

    # --- A value set over IPC outranks the file only until released (S6) --------------------------
    subprocess.run([ctl, "set", "center_width", "50"], check=True, stdout=log)
    hand_edit(layout, layout.read_text().replace("center_width = 35.000", "center_width = 37")
              .replace("goo_thickness = 13", "goo_thickness = 15"))
    check("the edit reloaded", option_reaches("goo_thickness", 15))
    check("an IPC-set value still holds before release", abs(option("center_width") - 50) < .01)
    released = json.loads(subprocess.check_output([ctl, "release"], text=True))
    check("scottland-ctl release reports what it released", released.get("released", 0) >= 1)
    check("after release the file wins", option_reaches("center_width", 37))
finally:
    for proc in clients:
        if proc.poll() is None:
            proc.terminate()
            proc.wait(timeout=5)
    with assembled.open("w") as out:
        out.write(base)
    log.close()
    sock.close()
print(f"{passed} passed; {failed} failed", flush=True)
raise SystemExit(bool(failed))
